service: lambda-mqtt

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  environment:
    AWS_IOT_HOST: ${env:AWS_IOT_HOST}

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: test
          method: get
